### ISSUE TITLE
CDN hosting of lib

### ISSUE THREAD

**Issue by puppetmaster3** [corinis/jsForm#13]
I use this CDN for fetching your lib:
http://www.jsdelivr.com/?query=jsForm
They have old version. 

Can you please ping them to host the new version.

**Comment by corinis** [comment]
I tried pinging, did not get any response there. 
If someone knows an easy to use cdn, I will happily try to get them to host jsForm, until then I will close this.

**Comment by puppetmaster3** [comment]
http://www.jsdelivr.com/ on home page has a 'host here' button.
