### ISSUE TITLE
Removing nested element removes enclosing group

### ISSUE THREAD

**Issue by ncelerier** [corinis/jsForm#15]
Hello,

It looks like there is a bug when you delete nested elements.

Have a look at this plunker: http://plnkr.co/edit/WKAbvq5npfAB0EpCes1o?p=preview. It is based on the "sortable-editable-sample" demo. I have just changed spans to buttons to make it more clear.

Then try to hit the "delete row" buttons. When it is working properly, only the row is removed. But when it is not working properly, the group is removed.

It is working properly with 1.3.1 and the version that runs the demo (which is not the latest, don't know which one it is). It is not working properly since 1.3.2.

I have copied some versions into the plunker so that you can easily enable or disable them to check.

Could you have a look at the problem ? 
Could you also use the latest version in the demos ? 

Thank you for your help !

**Comment by corinis** [comment]
fix in 1.3.6. it was an issue with the way events were handled

**Comment by ncelerier** [comment]
Thanks you for the fix ! :-)
