### ISSUE TITLE
Demo site is broken - blocked:mixed-content

### ISSUE THREAD

**Issue by atrost** [corinis/jsForm#16]
The demo page  (https://www.gargan.org/jsform/index.jsp) is currently useless because it uses mixed HTTPS with HTTP for downloading a page's content. More specifically, it attempts to load jquery.min.js from unsecured channel (using http) while other files are loaded from secure, https sources.

**Comment by corinis** [comment]
updated to https - thanks

**Comment by atrost** [comment]
Odd, still seeing the issue:
 
Mixed Content: The page at 'https://www.gargan.org/jsform/index.jsp' was loaded over HTTPS, but requested an insecure script 'http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js'. This request has been blocked; the content must be served over HTTPS.
jquery.jsForm.js:2276 Uncaught ReferenceError: jQuery is not defined
    at jquery.jsForm.js:2276
(anonymous) @ jquery.jsForm.js:2276
sample.html:6 Uncaught ReferenceError: $ is not defined
    at sample.html:6

**Comment by corinis** [comment]
I just double checked, no more reference to http, maybe you still have an old version in the cache (try clearing the cache)
