### ISSUE TITLE
Can't clear object for new data on same form with ajax

### ISSUE THREAD

**Issue by devWaleed** [corinis/jsForm#17]
@corinis  How do I reset data/form for new data? How do I get rid of data prefix?

I send an AJAX request on a btn click to fetch some data and then show a Bootstrap modal with a form. I fill that form with the data from AJAX response and on submit, I send the updated data from form using

```$("#editForm").jsForm("get");```

to server and modal closes. If I click edit btn again, I get new data from AJAX request but calling fill or changing data attribute with new data on same form doesn't work. It still shows old data from previous request.

If I clear the form using clear parameter, it will clear the form but on next request it won't populate anything in form.

```
$.get('ajax.get.php?type=1&lender_id='+id, function(response){

	response = JSON.parse(response);

	loading(false);

        // filling data object
	$("#editForm").jsForm({ data: response.lender });
	$("#editModal").modal('show');

});
```

**Comment by corinis** [comment]
One thing that stands out is, that you do not initialize the form correctly, this needs to be done "outside" if the ajax request (best to do it in a global context):

```
$(function() {
   $("#editForm").jsForm();
});
```

Next, you dont fill the form correctly, you need to call the "fill" function:

```
// filling data object
$("#editForm").jsForm("fill", response.lender);
```

you do not need to prefix the json with "data", the prefix is meant for the html.

I.e. (with default settings) you have a json like:
```
{ "name": "me", "street": "samplestreet" }
```
the corresponding form needs to be

```
<div id="editForm">
<input name="data.name"/><br/>
<input name="data.street"/>
</div>
```

so input[name='data.X'] is mapped to {X:""}.

The prefix is for the html for jsform to know which form elements to bind to, and which to ignore. You can mix multiple forms within a div and have jsform only bind to parts of it.

Calling jsForm with an object (like you do in)
```
$("#editForm").jsForm({ data: response.lender });
```

causes it to re-initialize with the configuration options (your data) :), the call without any "function name" is the constructor.
